#!/usr/bin/env bash

. panic
. config

INF=9223372036854775807

# Find last match for pattern in $title
lastMatch() {
    grep -Pbo "$1" <<< "$title" | tail -n 1
}

# Allow only alphanumeric, spaces and slashes, then lowercase and replace all spaces with dashes.
slugify() {
    sed -r 's/[^a-zA-Z0-9 \/]//g; s/.*/\L&/g; s/ +/-/g;' <<< "$1"
}

[[ -n $1 ]] || panic 'Usage: names <filename>'

srcName="$1"
baseName="${srcName##*/}"
# typeName given by last directory, Movies or Shows.
typeName="${srcName%/*}"
typeName="${typeName##*/}"

# Extract title from filename:
# Remove file extension and commonly interspersed words.
# Replace any number of spaces, dots, underscores, dashes, brackets, parenthesis and braces with single spaces.
# Title case.
title=$(sed -r "s/($COMMON_WORDS)//gi; s/[][ \.\_()\{\}-]+/ /g; s/.*/\L&/; s/[a-z]*/\u&/g" <<< "${baseName%.*}")

# Find year.
y=$(lastMatch '(?<= )\d{4}(?= |$)')
year=${y#*:}
yearPos=${y%:*}

# Find resolution.
r=$(lastMatch '(?<= )\d+P(?= |$)')
res=${r#*:}
resPos=${r%:*}
[[ -n $resPos && ${res:0:-1} -gt 1080 ]] && res="1080p"

# If file in Shows dir, find episode and put in series dirs.
if [[ "$typeName" = "$SHOWS_NAME" ]]; then
    e=$(lastMatch '(?<= |^)S\d+E\d+[^ ]*')
    episode=${e#*:}
    episodePos=${e%:*}
    if [[ -n $episodePos ]]; then
        showName="${title:0:episodePos-1}"
        series=${episode%E*}
        remoteDirName="$typeName/$showName/$showName $series"
    fi
else
    remoteDirName="$typeName"
fi

# Use only the characters up to the year or resolution unless year before episode.
[[ $episodePos -gt $yearPos || -n $resPos && $resPos -lt $yearPos || -z $yearPos ]] && cutPos=$resPos || cutPos=$yearPos
[[ -z $cutPos ]] && cutPos=$episodePos
if [[ -n $cutPos ]]; then
    cutPos=$((cutPos - 1))
    title="${title:0:cutPos}"
fi

# Ensure correct remoteDir
[[ -z "$remoteDirName" ]] && remoteDirName="$typeName/$title"
[[ "$remoteDirName" = "$baseName" ]] && remoteDirName='';

# Build destination filename, dstName.
dstName="$title"
# Add year.
if [[ ${#year} -gt 1 ]]; then
    title="$title ($year)"
    dstName="$dstName $year"
fi

# Add resolution.
[[ ${#res} -gt 1 ]] && dstName="$dstName $res"

# Slugify
[[ $SLUG_FNAME -gt 0 ]] && dstName="$(slugify "$dstName")"
[[ $SLUG_DIR -gt 0 ]] && remoteDirName="$(slugify "$remoteDirName")"

dstName="$dstName.mp4"
echo -e "$remoteDirName\t$dstName\t$title"
