#!/usr/bin/env bash

. panic
. config

[[ -n $1 ]] || panic "Usage: process-one ${SRC}/[filename] [?forceEncode]"
localName="$1"
relName=$(sed -r "s|^$SRC||gi" <<< "$localName")

if IFS=$'\t' read -r -a line; then
    newName="${line[1]}"
    title="${line[2]}"
else
    panic "Couldn't get title"
fi < <(./names "$relName")

echo
./encode "$newName" "$title" "$localName" "$2" || panic "Couldn't encode"
