#!/usr/bin/env bash

. panic
. args
. config

usage() {
    panic "Usage: process-one [options] <${SRC}/inputFile> [FFmpeg options]\n\nOptions:\n --force\tforce encoding"
}

parseArgs 1 "$@"
IFS=$'\t' read -r dirName outputFile title < <(./names "$inputFile")
[[ -n "$title" ]] || panic "Couldn't get title"
./encode $forceEncode "$inputFile" "$outputFile" "$title" $ffArgs || panic "Couldn't encode"
