#!/usr/bin/env bash

. panic
. config

[[ -n $1 ]] || panic "Usage: process-one ${SRC}/[filename] [?forceEncode]"
localName="$1"
relName=$(sed -r "s|^$SRC||gi" <<< "$localName")

IFS=$'\t' read -r dirName newName title < <(./names "$relName")
[[ -n "$title" ]] || panic "Couldn't get title"

echo
./encode "$newName" "$title" "$localName" "$2" || panic "Couldn't encode"
