#!/usr/bin/env bash

srcName="$1"
dirName="${srcName%/*}"
baseName="${srcName##*/}"
# Chop off extension.
jobName="${baseName%.*}"
subsName="$jobName*.srt"

while IFS= read -r -d '' fName; do
    # Everything after jobName.
    sub="${fName##*"$jobName"}"
    # Chop off extension.
    sub="${sub%.*}"
    # Replace any number of spaces, dots, underscores, dashes, brackets, parenthesis and braces with single spaces.
    # Title case.
    # Trim.
    sub=$(sed -r "s/[][ \.\_()\{\}-]+/ /g; s/.*/\L&/; s/[a-z]*/\u&/g; s/^\s+|\s+$//g" <<< "$sub")
    # First word.
    lang="${sub%% *}"
    # Occurrence of word "Forced".
    forced=$(grep -o "Forced" <<< "$sub")
    echo -e "$fName\t$sub\t$lang\t$forced"
done < <(find "$dirName" -type f -name "$subsName" -print0)
