#!/usr/bin/env bash

floor() {
    awk "BEGIN{printf(\"%d\", $1)}"
}

probe() {
    ffprobe -v error -select_streams $1 -show_entries $2 -of csv=p=0 "$inputFile"
}

escape() {
    sed -r 's|[$!\\`]|\\&|g' <<< "$1"
}

notNumeric() {
    awk -v a="$1" 'BEGIN{exit(a==a+0)}'
}

scan() {
        ffprobe -v error -select_streams $1:0 -show_entries packet=size,duration_time "$inputFile" | \
        awk -F= '/duration_time/ {duration += $2}
        /size/ {bytes += $2}
        END {printf("%d\n", bytes*8 / duration)}'
}

scanPeak() {
    ffprobe -v error -select_streams $1:0 -show_entries packet=size,duration_time "$inputFile" | \
    awk -F= -v BUFFER_SECONDS="$V_BUFFER_SECONDS" '/duration_time/ {
        times[i] = $2
        duration += $2
    }
    /size/ {
        sizes[i++] = $2
        bytes += $2
        while (duration > BUFFER_SECONDS) {
            duration -= times[s]
            bytes -= sizes[s++]
        }
        rate = bytes/duration
        if(rate > maxRate) maxRate=rate
    }
    END {printf("%d\n", maxRate*8)}'
}

# Allow only alphanumeric, spaces and slashes, then lowercase.
lower() {
    sed -r 's/[^a-zA-Z0-9 \/]//g; s/.*/\L&/g' <<< "$1"
}

# Replace multiple contiguous spaces with single spaces and trim space.
space() {
    sed -r 's/ +/ /g; s/(^ | $)//g' <<< "$1"
}
